//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Menu
    {
        public long Id { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập tên menu")]
        public string Text { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập đường đẫn của menu")]
        public string Link { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập kiểu chọn khi click")]
        public string Target { get; set; }
        public Nullable<int> TypeID { get; set; }
    
        public virtual MenuType MenuType { get; set; }
    }
}
