//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class NhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCungCap()
        {
            this.SanPham = new HashSet<SanPham>();
        }
    
        public string MaNCC { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập tên nhà cung cấp")]
        public string TenNCC { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập địa chỉ nhà cung cấp")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập sđt nhà cung cấp")]
        public string SoDienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}
