//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.DonDatHang = new HashSet<DonDatHang>();
        }
    
        public string MaNV { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập họ của nhân viên")]
        public string HoNV { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập tên của nhân viên")]
        public string TenNV { get; set; }
        [Required(ErrorMessage = "Mời bạn chọn giới tính")]
        public Nullable<bool> GioiTinh { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập ngày sinh")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập vào lương")]
        public Nullable<int> Luong { get; set; }
        [Required(ErrorMessage = "Mời bạn chọn ảnh")]
        public string AnhNV { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập số điện thoại")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập địa chỉ")]
        public string DiaChi { get; set; }
        public string Email { get; set; }
        [Required(ErrorMessage = "Mời bạn chọn bộ phận")]
        public string MaBP { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập mã tài khoản")]
        public Nullable<long> UserID { get; set; }
    
        public virtual BoPhan BoPhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHang { get; set; }
        public virtual QuanTri QuanTri { get; set; }
    }
}
