//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class QuanTri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuanTri()
        {
            this.KhachHang = new HashSet<KhachHang>();
            this.NhanVien = new HashSet<NhanVien>();
        }
    
        public long Id { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập tên tài khoản")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập mật khẩu")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập họ tên")]
        public string HoTen { get; set; }
        public string DienThoai { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập email")]
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> Quyen { get; set; }
        public bool TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanVien { get; set; }
    }
}
