//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDatHang = new HashSet<ChiTietDatHang>();
            this.ChiTietKho = new HashSet<ChiTietKho>();
        }
    
        public long MaSP { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập tên sản phẩm")]
        public string TenSP { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập tiêu đề title")]
        public string MetaTitle { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập số lượng")]
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        [Required(ErrorMessage = "Mời bạn chọn hình ảnh")]
        public string HinhAnh { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập mô tả sản phẩm")]
        public string MoTa { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập chi tiết sản phẩm")]
        public string ChiTiet { get; set; }
        public Nullable<int> ThoiHanBaoHanh { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgaySanXuat { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập người tạo")]
        public string TaoBoi { get; set; }
        [Required(ErrorMessage = "Mời bạn chọn danh mục sản phẩm")]
        public Nullable<long> DanhMucSanPhamID { get; set; }
        [Required(ErrorMessage = "Mời bạn chọn nhà cung cấp")]
        public string MaNCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatHang> ChiTietDatHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKho> ChiTietKho { get; set; }
        public virtual DanhMucSanPham DanhMucSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
